@baseUrl = http://localhost:6001

### 查看所有用户
GET {{baseUrl}}/findUsers

### 注册用户
POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "fg",
  "password": "fengfengpa"
}

### 登录用户
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "fg",
  "password": "fengfengpa"
}

### 个人信息
GET {{baseUrl}}/user/profile
Authorization: Bearer xxx

